AviSharmaaa/Hacktoberfest_2021

javascript/CountdownTimer/index.html
javascript/CountdownTimer/script.js
javascript/CountdownTimer/style.css

create a countdown timer using javascript

javascript countdown

---

python/password-generator/main.py

Password generator with python

added python password generator

---

java/String Anagram Check.java

Added String Anagram Check Question in java folder. please approve my PR

created String Anagram Check.java

---

cpp/Clock.cpp

A C++ project on a real-time working Clock

Clock Project in CPP

---

java/insertionSort.java

Added insertion sort program to sort an array in Java folder

Added insertion sort program to sort an array in Java folder

---

java/FordFulkerson.java

Ford-Fulkerson algorithm in java lang hope you support me by adding hacktoberfest label

Added Ford-Fulkerson algorithm in java

---

java/Sort.java

Program to compare the time taken in Quick Sort, Merge Sort, Bubble Sort with huge dataset

Sorting algorithms

---

java/HeapSort.java

Added HeapSort Algorithm in Java lang, kindly support by adding hacktoberfest label too if possible

Added HeapSort Algorithm

---

java/PermutationOfString.java

permutation of string programme in java. please accept my PR

permutation of string in java

---

c/btreeInsertion.c

Added a C program for insertioning key in a B- Tree. Contribution for hacktoberfest

Added a C program for B- Tree insertion

---

cpp/Dynamic Programming/maximalSquare.cpp

I have added the solution with clean and commented code along with sample test case for Maximal Square Problem. In this problem we have to find the square with max area consisting of all 1's in a 2D binary matrix.
Issue- #41

Add Maximal Square Problem under Dynamic Programming in C++

---

python/CoVID19 Info/Covid19_Info.py

I have added a script for checking CoVID19 cases in the world or any country. I am using the concept of web scraping for fetching the data from a website called `worldometers`. I am using bs4 and requests library with python to achieve this task.

checking live CoVID19 cases using python

---

c/Longest_Common_Subsequence.c

LCS is a technique in which we find a common string between the 2 given strings and print it. Here, I solved the LCS coding problem using the C programming language.

Coding and Solving Longest Common Subsequence

---

c/2d_array_spriral_print.c

C Program that prints a 2D array in spiral order.

Prints 2D array in a spiral order

---

c/insertionRedBlk.c

Following code is a C program for implementing red black tree, inserting node, deleting it

Added a C program for insertion in red black tree

---

cpp/Dynamic Programming/StrassenMultiply.cpp

Hello!
Added CPP Program to perform Matrix Multiplication using Strassen Algorithm (Dynamic Approach)

Added Strassen Multiplication Program

---

c/fordFulkerson.c

The following is a C program for implementing Ford-Fulkersion Algorithm

Added a C program for Ford-fulkerson Algorithm

---

BubbleSort

Bubble sort algorithm optimised way using java, check it out and do tell me if any change is required.

Optimised bubble Sort

---

python/Calculator using Tinker/main.py

I am contributing my calculator project using tinker GUI on python

This is a GUI Calculator

---

Snake Game/Snake Game using python/README.md
Snake Game/Snake Game using python/Snake_game.py

Adding Snake Game using Python

---

c/NAIVE-DICTIONARY-PALINDROME.c

A simple brute forced program to print the count of dictionary palindromes in a give file.

NAIVE-DICTIONARY-PALINDROME

---

python/Data Structures/Linked List/linkedlist.py
python/Data Structures/Stack/balanced.py
python/Data Structures/Stack/stack.py

Linked List and Stack implementation in Python along with basic operations.

Linked List and Stack in Python

---

c/binarySearchTime.c

Added a C program code for binary search with time analysis i.e. time taken

Added a C program for Binary Search with time Analysis
